Some code needs to be changed
The existing code of the example is not working, I have changed something so please review and confirm it.
First thing Here is creating main by extending App within another object so when we run it, it will through an error which is mentioned below  - 
Error: Could not find or load main class docs.http.scaladsl.server.MyExplicitExceptionHandler.MyApp

and the second thing is no need to define the object within object if we do so then application terminates the execution